# Generated by Django 2.0.5 on 2018-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=5)),
                ('station', models.CharField(max_length=5)),
                ('defect', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
