# Generated by Django 2.0.5 on 2018-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='takt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('2', '2'), ('3', '3')], max_length=1)),
                ('station', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('P', 'P'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('takt', models.CharField(choices=[('1/4', '1/4'), ('1/2', '1/2'), ('Full', 'Full')], max_length=4)),
                ('made_or_missed', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='line',
            field=models.CharField(choices=[('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='defect',
            name='station',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('P', 'P'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
    ]
