# Generated by Django 2.0.5 on 2018-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180726_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takt',
            name='made_or_missed',
        ),
        migrations.AddField(
            model_name='takt',
            name='made_takt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='takt',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
