# Generated by Django 2.0.5 on 2018-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180726_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='takt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
