# Generated by Django 2.0.5 on 2018-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180727_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='takt',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='takt',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
