# Generated by Django 2.0.5 on 2018-07-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180727_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='takt',
        ),
    ]
