# Generated by Django 2.0.5 on 2018-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='day_of_week',
            field=models.TextField(default='Monday'),
        ),
    ]
