# Generated by Django 2.0.5 on 2018-07-30 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180730_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 13, 0, 56, 949992), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Cheyenne', 'Cheyenne'), ('Tomahawk', 'Tomahawk'), ('Williams', 'Williams')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='value_stream',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('VS1', 'VS1'), ('VSO', 'VSO'), ('VSS', 'VSS'), ('VSRV', 'VSRV'), ('VSQ', 'VSQ')], null=True),
        ),
    ]
