# Generated by Django 2.0.5 on 2018-07-30 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20180730_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 13, 4, 28, 646144), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plant',
            field=models.CharField(blank=True, choices=[('Cheyenne', 'Cheyenne'), ('Tomahawk', 'Tomahawk'), ('Williams', 'Williams')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='value_stream',
            field=models.CharField(blank=True, choices=[('VS1', 'VS1'), ('VSO', 'VSO'), ('VSS', 'VSS'), ('VSRV', 'VSRV'), ('VSQ', 'VSQ')], max_length=5, null=True),
        ),
    ]
