# Generated by Django 2.0.5 on 2018-07-30 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20180730_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 14, 14, 59, 384210), null=True),
        ),
    ]
