# Generated by Django 2.0.5 on 2018-07-31 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20180730_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 31, 11, 26, 42, 287867, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='day_of_week',
            field=models.CharField(default='Tuesday', max_length=10),
        ),
    ]
