# Generated by Django 2.0.5 on 2018-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20180731_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='process_step',
            field=models.CharField(blank=True, choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Frame', 'Frame'), ('Roof', 'Roof'), ('Floor', 'Floor'), ('Final', 'Final')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
