# Generated by Django 2.0.5 on 2018-07-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20180731_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='process_step',
            field=models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Frame', 'Frame'), ('Roof', 'Roof'), ('Floor', 'Floor'), ('Final', 'Final')], max_length=10, null=True),
        ),
    ]
