# Generated by Django 2.0.5 on 2018-08-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_defect_process_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='day_of_week',
            field=models.CharField(default='Wednesday', max_length=10),
        ),
    ]
