# Generated by Django 2.0.5 on 2018-08-02 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20180801_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(default=datetime.date(2018, 8, 2), null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='day_of_week',
            field=models.CharField(default='Thursday', max_length=10),
        ),
    ]
