# Generated by Django 2.0.5 on 2018-08-09 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20180802_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartDefect',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('data.defect',),
        ),
        migrations.AlterField(
            model_name='defect',
            name='date_created',
            field=models.DateField(default=datetime.date(2018, 8, 9), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plant',
            field=models.CharField(blank=True, choices=[('Williams', 'Williams'), ('Cheyenne', 'Cheyenne'), ('Tomahawk', 'Tomahawk')], max_length=10, null=True),
        ),
    ]
